language: ruby

rvm:
  - '1.8.7'
  - '2.1.8'
  - '2.2.4'
  - '2.3.1'
  - '2.4.1'

gemfile:
  - 'Gemfile.2.3.mysql2'
  - 'Gemfile.3.2.mysql2'
  - 'Gemfile.4.2.mysql2'
  - 'Gemfile.4.2.pg'
  - 'Gemfile.5.1.mysql2'
  - 'Gemfile.5.1.pg'

matrix:
  exclude:
    - gemfile: 'Gemfile.2.3.mysql2'
      rvm: '2.1.8'
    - gemfile: 'Gemfile.2.3.mysql2'
      rvm: '2.2.4'
    - gemfile: 'Gemfile.3.2.mysql2'
      rvm: '2.3.1'
    - gemfile: 'Gemfile.2.3.mysql2'
      rvm: '2.3.1'
    - gemfile: 'Gemfile.2.3.mysql2'
      rvm: '2.4.1'
    - gemfile: 'Gemfile.3.2.mysql2'
      rvm: '2.4.1'
    - gemfile: 'Gemfile.4.2.mysql2'
      rvm: '1.8.7'
    - gemfile: 'Gemfile.4.2.pg'
      rvm: '1.8.7'
    - gemfile: 'Gemfile.4.2.mysql2'
      rvm: '2.4.1'
    - gemfile: 'Gemfile.4.2.pg'
      rvm: '2.4.1'
    - gemfile: 'Gemfile.5.1.mysql2'
      rvm: '1.8.7'
    - gemfile: 'Gemfile.5.1.mysql2'
      rvm: '2.1.8'
    - gemfile: 'Gemfile.5.1.pg'
      rvm: '1.8.7'
    - gemfile: 'Gemfile.5.1.pg'
      rvm: '2.1.8'

services:
  - mysql

install:
  # Replace default Travis CI bundler script with a version that doesn't
  # explode when lockfile doesn't match recently bumped version
  - bundle install --no-deployment --jobs=3 --retry=3 --path=${BUNDLE_PATH:-vendor/bundle}


before_script:
  - psql -c 'create database edge_rider_test;' -U postgres
  - mysql -e 'create database IF NOT EXISTS edge_rider_test;'

script: bundle exec rake current_rspec

notifications:
  email:
    - fail@makandra.de
